//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterUser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public int Id { get; set; }
        public string Usename { get; set; }
        public string Password { get; set; }
        public string Confirm_Password { get; set; }
        public string Name { get; set; }

        
        public System.DateTime DateOfBirth { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public int IsActive { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
